# Generated by Django 5.0.2 on 2024-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tvswarranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvswarranty',
            name='email',
            field=models.CharField(max_length=112),
        ),
    ]
