# Generated by Django 5.0.2 on 2024-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_olas1pro_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='olas1pro',
            name='brandname',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
