# Generated by Django 5.0.2 on 2024-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_olas1pro_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olas1pro',
            name='brandname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
