# Generated by Django 5.0.2 on 2024-03-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_olas1pro_brandname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atherwarranty',
        ),
        migrations.DeleteModel(
            name='Bajajwarranty',
        ),
        migrations.DeleteModel(
            name='Herowarranty',
        ),
        migrations.DeleteModel(
            name='Hondawarranty',
        ),
        migrations.DeleteModel(
            name='Olawarranty',
        ),
        migrations.DeleteModel(
            name='Riverindiewarranty',
        ),
        migrations.DeleteModel(
            name='Suzukiwarranty',
        ),
        migrations.DeleteModel(
            name='Viviprowarranty',
        ),
        migrations.DeleteModel(
            name='Yamahawarranty',
        ),
        migrations.AddField(
            model_name='tvswarranty',
            name='brandname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
